"""Ajout de la colonne max_gagnants dans Settings

Revision ID: 6cbbefb794d4
Revises: f20d1b0ed077
Create Date: 2024-10-14 18:31:20.288276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbbefb794d4'
down_revision = 'f20d1b0ed077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_gagnants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('max_gagnants')

    # ### end Alembic commands ###
