"""Ajout des champs numbers_proximity et stars_proximity dans Participant

Revision ID: 8747fb6af7b8
Revises: ccf7e848ba23
Create Date: 2024-10-14 20:39:55.352218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8747fb6af7b8'
down_revision = 'ccf7e848ba23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numbers_proximity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stars_proximity', sa.Integer(), nullable=True))
        batch_op.drop_column('proximity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('stars_proximity')
        batch_op.drop_column('numbers_proximity')

    # ### end Alembic commands ###
