"""Ajout de la colonne proximity

Revision ID: ccf7e848ba23
Revises: 6cbbefb794d4
Create Date: 2024-10-14 20:01:20.813161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf7e848ba23'
down_revision = '6cbbefb794d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('proximity')

    # ### end Alembic commands ###
