"""Ajout des colonnes selection_numeros et selection_etoiles

Revision ID: f20d1b0ed077
Revises: 
Create Date: 2024-10-13 21:16:05.141444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f20d1b0ed077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tirage')
    op.drop_table('participant')
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('max_participants', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jackpot_amount', mysql.FLOAT(), nullable=True),
    sa.Column('max_numeros', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_etoiles', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('participant',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('numeros', sa.BLOB(), nullable=True),
    sa.Column('etoiles', sa.BLOB(), nullable=True),
    sa.Column('gain', mysql.FLOAT(), nullable=True),
    sa.Column('match_numeros', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('match_etoiles', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tirage',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numeros', sa.BLOB(), nullable=True),
    sa.Column('etoiles', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
